### PR TITLE
Validation

### PR DESCRIPTION
**Pull request by Theophile-Kango**
Creation of a web page which resembles with the former apple home page
Welcome to your corrections and suggestions

### CODE REVIEW

**Review by rOluochKe — CHANGES_REQUESTED** [review]
@Theophile-Kango 
### You have done well so far, however, there are a number of issues you need to work on for your project to be approved.

- The thumbnail images need spacing in between, refer the [original website](https://web.archive.org/web/20140301004610/http://www.apple.com/)
- Write a more descriptive readme file [check this guide](https://github.com/microverseinc/readme-template)
- remove the ad in the header, it is not required
add
- Your navigation is off, replicate the reference website, logo, search, menu items, font and gradient and background
- Write a detailed pull request, ie what the project is about and what you have done [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
- You repeated content on the banner
reapted
- Make your footer better, [check the original site](https://web.archive.org/web/20140301004610/http://www.apple.com/)
footer

### Once you have made all these changes, resubmit for another review. I wish you all the best in your next submission.

**Comment by Theophile-Kango** [comment]
What do you mean by remove the ad in the header?
Do you ask to remove all the header section?

**Comment by Theophile-Kango** [comment]
> @Theophile-Kango
> 
> ### You have done well so far, however, there are a number of issues you need to work on for your project to be approved.
> * The thumbnail images need spacing in between, refer the [original website](https://web.archive.org/web/20140301004610/http://www.apple.com/)
> * Write a more descriptive readme file [check this guide](https://github.com/microverseinc/readme-template)
> * remove the ad in the header, it is not required
>   add
> * Your navigation is off, replicate the reference website, logo, search, menu items, font and gradient and background
> * Write a detailed pull request, ie what the project is about and what you have done [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> * You repeated content on the banner
>   reapted
> * Make your footer better, [check the original site](https://web.archive.org/web/20140301004610/http://www.apple.com/)
>   footer
> 
> ### Once you have made all these changes, resubmit for another review. I wish you all the best in your next submission.

What do you mean by remove the ad in the header?
Do you ask to remove all the header section?

**Comment by rOluochKe** [comment]
> > @Theophile-Kango
> > ### You have done well so far, however, there are a number of issues you need to work on for your project to be approved.
> > 
> > * The thumbnail images need spacing in between, refer the [original website](https://web.archive.org/web/20140301004610/http://www.apple.com/)
> > * Write a more descriptive readme file [check this guide](https://github.com/microverseinc/readme-template)
> > * remove the ad in the header, it is not required
> >   add
> > * Your navigation is off, replicate the reference website, logo, search, menu items, font and gradient and background
> > * Write a detailed pull request, ie what the project is about and what you have done [check this guide](https://microverse.pathwright.com/library/fast-track-curriculum/69047/path/step/66243642/)
> > * You repeated content on the banner
> >   reapted
> > * Make your footer better, [check the original site](https://web.archive.org/web/20140301004610/http://www.apple.com/)
> >   footer
> > 
> > ### Once you have made all these changes, resubmit for another review. I wish you all the best in your next submission.
> 
> What do you mean by remove the ad in the header?
> Do you ask to remove all the header section?

### Check point three, with the image screen shot

**Review by rOluochKe — CHANGES_REQUESTED** [review]
### Good job, I like what you have done so far. However, you need to fix a few issues.

- In your banner, this line is bouncing every time I hover over it (Watch the "Your Verse" film and explore the stories) and the text looks squeezed. 
distorted
- In your footer, `index.html` use best practices. Instead, use `<ul><li></li></ul>`
list items

### Again, solve the issues and resubmit for review. I wish you all the best in the next submission.

**Review by rOluochKe — APPROVED** [review]
### Good job guys, you have finally made it look good.

### I approve of this project. 

### You can move on to the next project, I wish you all the best

**Comment by Theophile-Kango** [comment]
Thank you

**Pull request merged**
